imports_granularity = "Crate"
struct_lit_single_line = true
unstable_features = true
version = "Two"
group_imports = "StdExternalCrate"
reorder_imports = true
wrap_comments = true
normalize_comments = true
reorder_impl_items = true
condense_wildcard_suffixes = true
use_field_init_shorthand = true
format_strings = true
format_code_in_doc_comments = true
format_macro_matchers = true
struct_lit_width = 60