[package]
name = "dumper"
version = "0.3.1"
edition = "2021"

[dependencies.vmmap]
path = "../vmmap"
default-features = false

[dependencies.ptrsx]
path = "../ptrsx"
default-features = false
features = ["dumper"]

[dependencies.argh]
version = "0.1.12"
default-features = false
